### ISSUE TITLE
Implement smart redirect handling

### ISSUE THREAD

**Issue by smiakchilo** [exadel-inc/etoolbox-link-inspector#8]
Got feedback from one of the users that says:
> The tool outputs all 404s that it recognizes throughout the site, but it also includes links that are being redirected. Would it be possible to cross reference the redirect mapper tool before the results are generated?

Needs to be investigated:
- how does Link Inspector handle redirects? Is it capable of following redirect headers or does it report non-200 responses as "invalid"?
- can we distinguish between redirects to a legit address and to a "stub" or placeholder page like one saying "There's no such page"
- advanced: can we add a setting that helps to distinguish between "legitimate" and "illegal" pages not judging by the status code solely, but probably by title or some text mask.

**Comment by vihnatsenka** [comment]
It is investigated. Separate issues for implementation is created. Closing this.
